### ISSUE TITLE
securerandom and uri in request_authenticator.rb

### ISSUE THREAD

**Issue by tineyedev** [unsplash/tinplate#5]
Hello,

Do `securerandom` and `uri` need to be imported in `request_authenticator.rb`? It won't work for me otherwise.

Also, we would like to add tinplate to our list of [TinEye Commercial API libraries](https://services.tineye.com/developers/tineyeapi/libraries.html) if that's okay with you?

Thanks!

**Comment by aaronklaassen** [comment]
@tineyedev I'm having trouble replicating that problem - it's an easy addition, of course, but I'd like to figure out what's exactly going on. Can you give me an example?

And yeah that'd be great if you could add tinplate to your list.

**Comment by tineyedev** [comment]
Yes, here's the script I ran based on your documentation:

```
require 'tinplate'

Tinplate.configure do |config|
  config.public_key  = ""
  config.private_key = ""
  config.test        = true
end

tineye = Tinplate::TinEye.new
results = tineye.search(image_url: "https://tineye.com/images/meloncat.jpg")

results.total_results    # => 2
results.total_backlinks  # => 3
results.matches          # => an Array of matched images (see below)

results.matches.each do |match|
    puts match
end
```

and the output:

```
$ ruby test_tinplate.rb
/home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/tinplate-1.0.2/lib/tinplate/request_authenticator.rb:10:in `initialize': uninitialized constant Tinplate::RequestAuthenticator::SecureRandom (NameError)
```

It works if I add `require 'securerandom'` and `require 'uri'` to the script, but I think those should be added to the library. Does Rails import those by default?

**Comment by aaronklaassen** [comment]
Ah of course. Yeah I was running this either in Rails or via `bundle console`, in either case those libraries would be loaded. I'll get a fix out.

**Comment by aaronklaassen** [comment]
v1.0.3 is what you're lookin' for.

**Comment by tineyedev** [comment]
Thanks for the quick fix!
